### ISSUE TITLE
[DOC] - Typescript example is missing File[]

### ISSUE THREAD

**Issue by marcusflat** [viclafouch/mui-file-input#23]
On typescript section, the type of useState and handleChange newValue param is missing `File[]`;
```TS
import React from 'react'
import { MuiFileInput } from 'mui-file-input'

const MyComponent = () => {
  const [value, setValue] = React.useState<File | null>(null)

  const handleChange = (newValue: File | null) => {
    setValue(newValue)
  }

  return (
    <MuiFileInput
      value={value}
      onChange={handleChange}
      hideSizeText
    />
  )
}
```
I got the error: Type '(newValue: File | null) => void' is not assignable to type '(value: File | File[] | null) => void'.

The correct type is: `File | File[] | null`

[Doc Page](https://viclafouch.github.io/mui-file-input/docs/typescript/)

**Comment by viclafouch** [comment]
Issue has been fixed in `v2.0.4`, the typing was wrong in the code, not in the documentation.

## `onChange`

- Type: `(value: File | null) => void`
- or if `multiple` is present: `(value: File[]) => void`

Gets called once the user updates the file value.

Example:

```tsx

const handleChange = (value) => {}

<MuiFileInput onChange={handleChange} />
```

Thanks for the catch @marcusflat
